const cfg=window.SUPABASE_CONFIG||{};let db=null;
if(window.supabase&&cfg.url&&!cfg.url.startsWith("YOUR_")&&cfg.anonKey&&!cfg.anonKey.startsWith("YOUR_")) db=supabase.createClient(cfg.url,cfg.anonKey);
const EXP=["Chicken","Vegetables","Oil","Gas","Electricity","Rent","Salary","Transport","Packaging","Maintenance","Other"], INC=["Chicken sales","Food sales","Customer payment","Other income"], PAY=["Cash","UPI","Bank","Other"];
let S={page:location.hash.slice(1)||"dashboard",tx:[],loading:true,type:"all",date:"all",range:"month",edit:null};
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(+n||0);
const today=()=>{let d=new Date();d=new Date(d-d.getTimezoneOffset()*60000);return d.toISOString().slice(0,10)};
const sum=(a,t)=>a.filter(x=>x.type===t).reduce((s,x)=>s+ +x.amount,0);
const fmt=d=>new Date(d+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short"});
function toast(x){let e=document.querySelector("#toast");e.textContent=x;e.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>e.style.display="none",2200)}
function go(p){location.hash=p}
addEventListener("hashchange",()=>{S.page=location.hash.slice(1)||"dashboard";render()});
async function load(){if(!db){S.loading=false;render();return}S.loading=true;render();let q=await db.from("transactions").select("*").order("transaction_date",{ascending:false}).order("created_at",{ascending:false});S.loading=false;S.tx=q.data||[];S.error=q.error?"Could not load Supabase data. Check config/RLS.":"";render()}
function nav(){return `<nav class="bottom">${[["dashboard","⌂","Dashboard"],["transactions","☷","Transactions"],["reports","◔","Reports"],["settings","⚙","Settings"]].map(a=>`<button class="${S.page===a[0]?"on":""}" onclick="go('${a[0]}')">${a[1]}<span>${a[2]}</span></button>`).join("")}</nav>`}
function card(l,n,c){return `<div class="card"><div class="amount ${c||""}">${money(n)}</div><div class="label">${l}</div></div>`}
function item(x){return `<div class="tx"><div class="txmain" onclick="form('${x.type}','${x.id}')"><div class="txname">${esc(x.description||x.category)}</div><div class="meta">${fmt(x.transaction_date)} · ${esc(x.payment_method)} · ${esc(x.category)}</div></div><div class="right"><b class="${x.type==="income"?"income":"expense"}">${x.type==="income"?"+":"-"}${money(x.amount)}</b><button class="del" onclick="del('${x.id}')">✕</button></div></div>`}
function list(a){return a.length?`<div class="list">${a.map(item).join("")}</div>`:`<div class="empty">No transactions yet.<br><small>Add your first income or expense to get started.</small></div>`}
function dashboard(){let a=S.tx.filter(x=>x.transaction_date===today()),i=sum(a,"income"),e=sum(a,"expense");return `<h1 class="title">Friends Chiken Pokadi</h1><p class="muted">${new Date().toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</p>${S.error?`<div class="error">${esc(S.error)}</div>`:""}${S.loading?`<div class="grid">${[1,2,3,4].map(()=>'<div class="loading"></div>').join("")}</div>`:`<div class="grid">${card("Today's Income",i,"income")}${card("Today's Expenses",e,"expense")}${card("Today's Profit",i-e)}${card("Balance",sum(S.tx,"income")-sum(S.tx,"expense"))}</div><div class="actions"><button class="btn green" onclick="form('income')">+ Add Income</button><button class="btn red" onclick="form('expense')">+ Add Expense</button></div><div class="section"><div class="head"><h2>Recent Transactions</h2><button class="link" onclick="go('transactions')">View All</button></div>${list(S.tx.slice(0,5))}</div>`}`}
function filtered(){let a=[...S.tx];if(S.type!=="all")a=a.filter(x=>x.type===S.type);let d=new Date(),t=today(),m=t.slice(0,7)+"-01",w=new Date(d);w.setDate(d.getDate()-d.getDay());let ws=new Date(w-w.getTimezoneOffset()*60000).toISOString().slice(0,10);if(S.date==="today")a=a.filter(x=>x.transaction_date===t);if(S.date==="month")a=a.filter(x=>x.transaction_date>=m);if(S.date==="week")a=a.filter(x=>x.transaction_date>=ws);if(S.date==="yesterday"){let y=new Date(d);y.setDate(d.getDate()-1);y=new Date(y-y.getTimezoneOffset()*60000).toISOString().slice(0,10);a=a.filter(x=>x.transaction_date===y)}return a}
function transactions(){let a=filtered();return `<h1 class="title">Transactions</h1><div class="chips">${["all","income","expense"].map(x=>`<button class="chip ${S.type===x?"active":""}" onclick="S.type='${x}';render()">${x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div><div class="chips">${["all","today","yesterday","week","month"].map(x=>`<button class="chip ${S.date===x?"active":""}" onclick="S.date='${x}';render()">${x==="all"?"All time":x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div>${S.loading?'<div class="loading"></div>':list(a)}`}
function reports(){let a=S.range==="all"?S.tx:S.tx.filter(x=>S.range==="today"?x.transaction_date===today():S.range==="month"?x.transaction_date>=today().slice(0,7)+"-01":x.transaction_date>=today());let i=sum(a,"income"),e=sum(a,"expense"),m={};a.filter(x=>x.type==="expense").forEach(x=>m[x.category]=(m[x.category]||0)+ +x.amount);let b=Object.entries(m).sort((a,b)=>b[1]-a[1]),max=b[0]?.[1]||1;return `<h1 class="title">Reports</h1><div class="chips">${["today","week","month","all"].map(x=>`<button class="chip ${S.range===x?"active":""}" onclick="S.range='${x}';render()">${x==="all"?"All time":x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div><div class="card"><div class="report"><span class="muted">Income</span><b class="income">${money(i)}</b></div><div class="report"><span class="muted">Expenses</span><b class="expense">${money(e)}</b></div><div class="report"><span>Profit</span><b>${money(i-e)}</b></div><div class="report"><span class="muted">Transactions</span><span>${a.length}</span></div></div><div class="section"><h2>Where money went</h2>${b.length?b.map(([k,v])=>`<div class="section"><div class="head"><span>${esc(k)}</span><b>${money(v)}</b></div><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(""):'<p class="muted">No expenses in this period.</p>'}</div>`}
function settings(){return `<h1 class="title">Settings</h1><div class="card section"><span class="muted">Business Name</span><b>Friends Chiken Pokadi</b></div><div class="card section"><span class="muted">Currency</span><b>₹ INR</b></div><div class="card section"><span class="muted">Expense Categories</span><div class="pills">${EXP.map(x=>`<span class="pill">${x}</span>`).join("")}</div></div>`}
function render(){document.querySelector("#app").innerHTML=S.page==="transactions"?transactions():S.page==="reports"?reports():S.page==="settings"?settings():dashboard();document.querySelector("#nav").innerHTML=nav()}
function form(type,id){let x=id?S.tx.find(t=>t.id===id):null,c=type==="income"?INC:EXP,p=x?.payment_method||"Cash";document.querySelector("#modal").innerHTML=`<div class="back"><div class="modal"><h2>${x?"Edit":"Add"} ${type}</h2><form onsubmit="save(event,'${type}','${id||""}')"><div class="field"><label>Amount *</label><input id="amt" type="number" min=".01" step=".01" required value="${x?.amount||""}"></div><div class="field"><label>${type==="income"?"Source":"Category"} *</label><select id="cat">${c.map(v=>`<option ${x?.category===v?"selected":""}>${v}</option>`).join("")}</select></div><div class="field"><label>Description</label><input id="desc" value="${esc(x?.description||"")}"></div><div class="field"><label>Date</label><input id="dt" type="date" value="${x?.transaction_date||today()}"></div><div class="field"><label>Payment Method</label><div class="pay">${PAY.map(v=>`<button type="button" class="${p===v?"sel":""}" onclick="this.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('sel'));this.classList.add('sel')">${v}</button>`).join("")}</div></div><div class="field"><label>Note</label><input id="note" value="${esc(x?.note||"")}"></div><div class="modal-actions"><button type="button" class="btn light" onclick="closeModal()">Cancel</button><button class="btn ${type==="income"?"green":"red"}">Save</button></div></form></div></div>`}
function closeModal(){document.querySelector("#modal").innerHTML=""}
async function save(e,type,id){e.preventDefault();if(!db){toast("Add Supabase URL/key in config.js");return}let pays=[...document.querySelectorAll(".pay button")],pay=pays.find(b=>b.classList.contains("sel"))?.textContent||"Cash";let p={type,amount:+document.querySelector("#amt").value,category:document.querySelector("#cat").value,description:document.querySelector("#desc").value,payment_method:pay,transaction_date:document.querySelector("#dt").value,note:document.querySelector("#note").value};let q=id?db.from("transactions").update(p).eq("id",id):db.from("transactions").insert(p);let r=await q;if(r.error){toast(r.error.message);return}closeModal();toast(id?"Updated":"Saved");load()}
async function del(id){if(!confirm("Delete this transaction?"))return;if(!db)return toast("Configure Supabase first");let r=await db.from("transactions").delete().eq("id",id);toast(r.error?"Could not delete":"Deleted");load()}
render();load();
if(db)db.channel("transactions-live").on("postgres_changes",{event:"*",schema:"public",table:"transactions"},()=>load()).subscribe();
